// backend/generate-tests.js
const TestWriterAgent = require('./src/agents/testwriter');
const fs = require('fs').promises;
const path = require('path');

async function generateProjectTests() {
  console.log('\n=== DAY 8: USING TESTWRITER AGENT TO GENERATE TESTS ===\n');
  console.log('This demonstrates ABBA agents building ABBA!\n');
  
  const testWriter = new TestWriterAgent();
  const agentsToTest = [
    { name: 'Orchestrator', file: './src/agents/orchestrator.js' },
    { name: 'Interpreter', file: './src/agents/interpreter.js' },
    { name: 'Architect', file: './src/agents/architect.js' },
    { name: 'Coder', file: './src/agents/coder.js' },
    { name: 'Validator', file: './src/agents/validator.js' }
  ];

  let totalTests = 0;
  let totalLines = 0;

  for (const agent of agentsToTest) {
    try {
      console.log(`Generating tests for ${agent.name} Agent...`);
      
      // Read agent code
      const code = await fs.readFile(agent.file, 'utf8');
      
      // Generate tests using TestWriter Agent
      const tests = await testWriter.generateTests(code, agent.name);
      
      // Count lines generated
      const linesGenerated = tests.split('\n').length;
      totalLines += linesGenerated;
      
      // Save test file
      const testPath = path.join(__dirname, 'tests', `${agent.name.toLowerCase()}.test.js`);
      await fs.writeFile(testPath, tests);
      
      console.log(`   Generated ${linesGenerated} lines of test code`);
      console.log(`   Saved to: tests/${agent.name.toLowerCase()}.test.js\n`);
      totalTests++;
      
    } catch (error) {
      console.error(`   ❌ Failed: ${error.message}\n`);
    }
  }
  
  console.log('='.repeat(60));
  console.log('TEST GENERATION COMPLETE - DOG FOODING SUCCESS!');
  console.log('='.repeat(60));
  console.log(`   Tests Generated: ${totalTests} files`);
  console.log(`   Total Lines of Test Code: ${totalLines}`);
  console.log(`   Generated by: TestWriter Agent (created on Day 4)`);
  console.log(`   Time Saved: ~${Math.round(totalLines / 50)} hours of manual writing`);
  console.log('='.repeat(60));
  console.log('\nThis proves ABBA can build and test itself!\n');
}

generateProjectTests();